/**
 * Generates `src/data/generated/index.ts` from the frontmatter of every problem MDX file.
 *
 * The app needs problem metadata (title, difficulty, patterns …) for list pages without
 * loading 150 MDX modules. The generated file is git-ignored and rebuilt by `npm run
 * content:index`, which `dev`, `build` and `typecheck` all run first.
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { CATEGORIES } from "../src/data/categories.ts";
import type { ProblemMeta } from "../src/data/types.ts";
import { collectProblems, GENERATED_DIR } from "./lib/collect.ts";
import { parseProblem } from "./lib/frontmatter.ts";

const OUTPUT = path.join(GENERATED_DIR, "index.ts");

export async function buildIndex(): Promise<{ count: number; skipped: string[] }> {
  const sources = await collectProblems();
  const metas: ProblemMeta[] = [];
  const skipped: string[] = [];

  for (const source of sources) {
    const { meta } = parseProblem(source);
    if (meta) metas.push(meta);
    else skipped.push(source.file);
  }

  metas.sort(byCategoryThenId);
  await mkdir(GENERATED_DIR, { recursive: true });
  await writeIfChanged(OUTPUT, render(metas));

  return { count: metas.length, skipped };
}

function byCategoryThenId(a: ProblemMeta, b: ProblemMeta): number {
  const order = (slug: string) => CATEGORIES.findIndex((c) => c.slug === slug);
  const byCategory = order(a.category) - order(b.category);
  if (byCategory !== 0) return byCategory;
  return compareIds(a.id, b.id);
}

function compareIds(a: string, b: string): number {
  const [aMajor = 0, aMinor = 0] = a.split(".").map(Number);
  const [bMajor = 0, bMinor = 0] = b.split(".").map(Number);
  return aMajor - bMajor || aMinor - bMinor;
}

function render(metas: ProblemMeta[]): string {
  return [
    "// AUTO-GENERATED by scripts/build-index.ts — do not edit, do not commit.",
    "",
    'import type { ProblemMeta } from "../types";',
    "",
    `export const PROBLEMS: readonly ProblemMeta[] = ${JSON.stringify(metas, null, 2)};`,
    "",
  ].join("\n");
}

/** Avoids touching the file when nothing changed, so the dev server does not reload in a loop. */
async function writeIfChanged(file: string, contents: string): Promise<void> {
  const current = await readFile(file, "utf8").catch(() => null);
  if (current === contents) return;
  await writeFile(file, contents, "utf8");
}

const isMain =
  process.argv[1] !== undefined &&
  import.meta.url === pathToFileURL(process.argv[1]).href;

if (isMain) {
  const { count, skipped } = await buildIndex();
  console.log(`content index: ${count} problem(s)`);
  for (const file of skipped) {
    console.warn(`  skipped (invalid frontmatter): ${file}`);
  }
}
